const BASE_URL="https://www.parrucchieriestetiste.it/magazzino/db"; 
//const BASE_URL="http://localhost:8888";
const locale_string = {
    name: "Nome",
    shops: "Negozi",
    description : "Descrizione",
    barcode : "Codice a barre",
    shop1: "Terracina",
    shop2: "B.go Hermada",
    initialPrice: "Prezzo d'acquisto",
    finalPrice: "Prezzo al dettaglio",
    wholesalePrice: "Prezzo all'ingrosso",
    quantity: "Quantità",
    brand: "Marca",
    delete_product: "Elimina Prodotto",
    change_product: "Aggiorna prodotto",
    add_product: "Aggiungi prodotto",
    general: "Generale",
    product_deleted: "Prodotto eliminato",
    product_updated: "Prodotto aggiornata",
    product_added: "Prodotto aggiunto",
    error: "Errore",
    delete: "Elimina",
    cart_store_at: "Carrello spesa a ",
    price: "Prezzo",
    adding_product: "Aggiungendo il prodotto",
    avaiability: "Disponibilità",
    show_all: "Mostra tutto",
    out_of_stock: "Terminati",
    availables: "Disponibili",
    products: "Prodotti",
    prices: "Prezzi",
    number_of_element_stored_in_: "Numero di elementi a ",
    select_a_brand: "Seleziona una marca",
    readBarcode: "Leggi il codice a barre",
    go_checkout: "Termina il conto",
    completeOrder: "Completa l'ordine",
    orderCompleted: "Acquisto completato",
    getIdClient: "Fidelity Card Number",
    add_brand: "Aggiungi marca",
    brand_added: "Marca aggiunta",
    loading: "Caricamento",
    per_cent_button20: "20%",
    per_cent_button0: "0%",
    sale: "Sconto"
}

exports.LOCALE_STRING = locale_string;
exports.BASE_URL = BASE_URL;